// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcmfmuiyycuozulrxyam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jbWZtdWl5eWN1b3p1bHJ4eWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzI1MzMsImV4cCI6MjA3NDAwODUzM30.nKTr5jJe9Ea5qGyT6RM4Ukh43vFRHNxSMwNCpzSD43M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    }
  }
});

